import "./account.css"
import AccountHeader from "./components/accountHeader";
import Activity from "./components/activity";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  return (
    <section className="section_account">

      <div className="continer_account w-100">
        <div className="box_layout">
          <div className="link_layout">
            <AccountHeader />
            <Activity />
          </div>
          {children}
        </div>
      </div>

    </section>

  );
}
