
import "../layout/css/globals.css"
import TabbedPage from "../layout/tabbedPage/tabbedPage";
import { vazir } from "../fonts/font";
import "bootstrap/dist/css/bootstrap.rtl.min.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {






  return (
    <html lang="fa" dir="rtl">
      <body className={`${vazir.className}`}>
        <div className="app w-100" >
          {children}
          <TabbedPage />
        </div>
      </body>
    </html>
  );
}
